[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./script"}]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
fuji = "${FUJI_RPC_URL}"

# [etherscan]
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# fuji = { key = "${ETHERSCAN_API_KEY}" }

[profile.nowarnings]

# ignore solc warnings for missing license and exceeded contract size
# known error codes are: ["unreachable", "unused-return", "unused-param", "unused-var", "code-size", "shadowing", "func-mutability", "license", "pragma-solidity", "virtual-interfaces", "same-varname"]
# additional warnings can be added using their numeric error code: ["license", 1337]
ignored_error_codes = ["unreachable", "unused-return", "unused-param", "unused-var", "code-size", "func-mutability", "license", "pragma-solidity", "virtual-interfaces", "same-varname"]
